// PIQUE Visualizer project page
import "../styles/EnvironmentalDashboard.css";
import MSU from "../assets/MSUlogo.jpg";
import wireframe1 from "../assets/PIQUE wireframe 1.png";
import wireframe2 from "../assets/PIQUE wireframe 2.png";
import wireframe3 from "../assets/PIQUE wireframe 4.png";
import final from "../assets/PIQUE single file 1.png";
import final1 from "../assets/PIQUE compare 2.png";
import final2 from "../assets/PIQUE project 1.png";

import Lightbox from "../components/Lightbox";
import React, { useState, KeyboardEvent } from "react";

// Small helper to avoid repeating handlers on every <img>
type ZoomableImgProps = {
  src: string;
  alt: string;
  className?: string;
  onZoom: (src: string, alt: string) => void;
};
const ZoomableImg: React.FC<ZoomableImgProps> = ({
  src,
  alt,
  className,
  onZoom,
}) => {
  const onKey = (e: KeyboardEvent<HTMLImageElement>) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      onZoom(src, alt);
    }
  };
  return (
    <img
      src={src}
      alt={alt}
      loading="lazy"
      className={className ? `${className}` : undefined}
      onClick={() => onZoom(src, alt)}
      onKeyDown={onKey}
      tabIndex={0}
      role="button"
      aria-label={`Open larger view: ${alt}`}
      style={{ cursor: "zoom-in" }}
    />
  );
};

const PIQUEViz: React.FC = () => {
  const [lbOpen, setLbOpen] = useState(false);
  const [lbSrc, setLbSrc] = useState<string | null>(null);
  const [lbAlt, setLbAlt] = useState("");

  const openLB = (src: string, alt: string) => {
    setLbSrc(src);
    setLbAlt(alt);
    setLbOpen(true);
  };

  return (
    <div className="project-details">
      <h2>PIQUE Visualizer</h2>
      <p className="project-summary">
        A web-based visualizer developed for clients who are wanting to view
        complex PIQUE output JSON files. Designed to provide high level
        information to inform stakeholders of software aspects resulting in low
        software quality.
      </p>

      <section className="project-section">
        <h3>Problem</h3>
        <p>
          PIQUE software quality assessment presents stakeholders with complex
          and long JSON files containing information related to software
          quality. Currently, no visualizer exists for the PIQUE software
          quality model that provides item-specific details or comparison of
          files to inform stakeholders about software aspects that are hindering
          software quality.
        </p>
      </section>

      <section className="project-section">
        <h3>Solution</h3>
        <p>
          I designed and developed a web-accessible visualizer that provides
          stakeholders with specific information related to their software that
          the PIQUE software quality model scores. The visualizer provides a
          streamlined experience for both developers and non-technical
          stakeholders. Its comparison view automatically highlights differing
          fields between files, while the score tracker displays changes across
          multiple versions to support long-term quality improvement.{" "}
        </p>
      </section>

      <section className="project-section">
        <h3>Benefits</h3>
        <p>
          The visualizer provides software developers information they need to
          fix software vulnerabilities and improve software quality based on
          outputs generated by the PIQUE software quality model.
        </p>
      </section>

      <section className="project-section">
        <h3>Tools</h3>
        <ul>
          <li>
            <strong>Low- & High-Fidelity Prototyping:</strong> Adobe XD
          </li>
          <li>
            <strong>Frontend Development:</strong> React + Vite
          </li>
          <li>
            <strong>Data Visualization (Static & Dynamic):</strong> D3.js,
            react-gauge-components, and Recharts
          </li>
          <li>
            <strong>Documentation:</strong> Docusaurus
          </li>
        </ul>
      </section>

      <section className="project-section">
        <h3>Brainstorming & Design Process</h3>

        <div className="subsection">
          <p>
            <strong>Stakeholder Meetings</strong> — Conducted individual and
            group sessions with key stakeholders during the
            requirements-gathering phase. Follow-up meetings ensured evolving
            design decisions continued to meet stakeholder needs.
          </p>
        </div>

        <div className="subsection">
          <p>
            <strong>Low- & High-Fidelity Prototyping</strong> — Created an
            initial layout and component arrangement to visualize PIQUE output
            data. High-fidelity prototyping in Adobe XD allowed stakeholders to
            preview interaction flow and provide usability feedback.
          </p>

          <figure className="project-figure">
            <ZoomableImg
              src={wireframe1}
              alt="Wireframe 1"
              className="project-image"
              onZoom={openLB}
            />
            <ZoomableImg
              src={wireframe2}
              alt="Wireframe 2"
              className="project-image"
              onZoom={openLB}
            />
            <ZoomableImg
              src={wireframe3}
              alt="Wireframe 3"
              className="project-image"
              onZoom={openLB}
            />
            <figcaption>
              <strong>Figure 1.</strong> Early mockups illustrating layout
              concept and component arrangement for the PIQUE Visualizer.
            </figcaption>
          </figure>

          <p>
            <a
              href="https://xd.adobe.com/view/1870bf09-5eb6-497a-b930-860a92633fb1-4d23/"
              target="_blank"
              rel="noopener noreferrer"
              className="project-link"
            >
              View high-fidelity prototype →
            </a>
          </p>
        </div>

        <div className="subsection">
          <p>
            <strong>Usability Heuristics</strong> — Applied color-blind
            accessibility principles, consistent labeling, and familiar
            interaction patterns to ensure inclusivity. The design also
            emphasized <em>visibility of system status</em> through live score
            gauges and comparison highlights, <em>user control and freedom</em>{" "}
            via reset and mode selection options, and <em>error prevention</em>{" "}
            through input validation and descriptive feedback when uploading
            files. Also applied <em>recognition rather than recall</em> by
            surfacing contextual labels, badges, and legends on each view, and{" "}
            <em>consistency &amp; standards</em> through uniform tab patterns,
            filter controls, and gauge semantics across pages. Finally, user
            documentation and tutorial videos were created to assist
            stakeholders in navigating the visualizer.
          </p>
        </div>

        <div className="subsection">
          <p>
            <strong>UX Laws</strong> — Guided by key UX principles, such as{" "}
            <em>Hick’s Law</em> to minimize decision effort,{" "}
            <em>Fitts’s Law</em> to make key actions easily selectable,{" "}
            <em>Miller’s Law</em> by grouping outputs (TQI, Quality Aspects,
            CWEs, Packages) to reduce cognitive load, and <em>Jakob’s Law</em>{" "}
            by following familiar dashboard conventions (tabs, filters,
            comparison diffing).
          </p>
        </div>

        <div className="subsection">
          <p>
            <strong>Usability Testing</strong> — Usability testing with
            stakeholders is planned to gather feedback on task flow,
            readability, and icon clarity.
          </p>
        </div>

        <div className="subsection">
          <strong>User Guides & Documentation </strong> — User guides and documention were generated
          to provide users guidence on the PIQUE Visualizer flow and use.

          <p>
            <a
              href=""
              target="_blank"
              rel="noopener noreferrer"
              className="project-link"
            >
              View user guide & documentation →
            </a>
          </p>
        </div>
      </section>

      <section className="project-section">
        <h3>Outcome</h3>
        <p>
          The final product provides both internal and external stakeholders
          with an intuitive visualizer to quickly see aspects of software
          quality. This provides stakeholders with insight on what aspects are
          hindering software quality and what actions they can take to improve
          their software quality.{" "}
          <strong>
            Note: This project is still ongoing and is not web accessible yet.
          </strong>
        </p>

        <figure className="project-figure">
          <ZoomableImg
            src={final}
            alt="Single file visual"
            className="project-image"
            onZoom={openLB}
          />
          <ZoomableImg
            src={final1}
            alt="Compare two files"
            className="project-image"
            onZoom={openLB}
          />
          <ZoomableImg
            src={final2}
            alt="Project page with score tracker and file list"
            className="project-image"
            onZoom={openLB}
          />
          <figcaption>
            <strong>Figure 2.</strong> Selected screenshots of the PIQUE
            Visualizer. Top figure shows the visual for a single file. Middle
            figure shows the comparison of two files. Bottom figure shows the
            project page with a score tracker, file list, and visualizer for a
            single file or comparison of two files.
          </figcaption>
        </figure>
      </section>

      <section className="project-section">
        <h3>Reflection</h3>
        <p>
          This project deepened my understanding of designing web-based
          visualizers that balance clarity for non-technical stakeholders with
          depth for engineers. Collaboration across teams improved my ability to
          translate feedback into concrete interaction patterns (e.g.,
          comparison highlights and reset/filters), communicate design
          rationale, and iterate quickly within technical constraints. Next, I’d
          perform user testing and run a short task-based study to quantify time
          saved when identifying regressions across versions.
        </p>
      </section>

      <hr />
      <div className="funding">
        <img className="ESS-logo" src={MSU} alt="MSU logo" />
        <div className="funding-text">
          This project was funded through the{" "}
          <a
            href="https://montana.edu/cyber"
            target="_blank"
            rel="noopener noreferrer"
          >
            Montana State University Software Engineering and Cybersecurity
            Laboratory
          </a>
          .
        </div>
      </div>

      <Lightbox
        open={lbOpen}
        src={lbSrc}
        alt={lbAlt}
        onClose={() => setLbOpen(false)}
      />
    </div>
  );
};

export default PIQUEViz;
